name: Vite Dev Server Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-dev-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Start dev server and test
      run: |
        npm run dev & 
        DEV_SERVER_PID=$!
        
        # Wait for the server to start (adjust the sleep time if needed)
        sleep 10
        
        # Check if the process is still running
        if ps -p $DEV_SERVER_PID > /dev/null
        then
          echo "Dev server started successfully"
          kill $DEV_SERVER_PID
          exit 0
        else
          echo "Dev server failed to start or crashed"
          exit 1
        fi
